---
server:
  address: "tcp://:9091"

telemetry:
  metrics:
    enabled: true
    address: "tcp://:9959"

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: '{{ env "AUTH_RESET_PASSWORD_JWT_SECRET" }}'

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml
    password:
      algorithm: argon2id
      iterations: 3
      memory: 65536
      parallelism: 4
      salt_length: 16
      key_length: 32

session:
  secret: '{{ env "AUTH_SESSION_SECRET" }}'
  expiration: 6h
  inactivity: 6h
  cookies:
    - domain: the-lab.zone
      authelia_url: https://auth.infra.the-lab.zone

storage:
  encryption_key: '{{ env "AUTH_STORAGE_ENCRYPTION_KEY" }}'
  local:
    path: /var/lib/authelia/db.sqlite3

access_control:
  default_policy: one_factor

notifier:
  filesystem:
    filename: /var/lib/authelia/notification.txt

identity_providers:
  oidc:
    hmac_secret: '{{ env "AUTH_OIDC_HMAC_SECRET" }}'
    jwks:
      - key: |
{{ secret "/etc/authelia/jwks.pem" | indent 10 }}
    claims_policies:
      grafana:
        id_token: ['email', 'name', 'groups', 'preferred_username']
    clients:
      - client_id: forgejo
        client_name: Forgejo
        client_secret: '{{ env "AUTH_FORGEJO_OIDC_CLIENT_SECRET" }}'
        consent_mode: implicit
        redirect_uris:
          - https://forgejo.the-lab.zone/user/oauth2/authelia/callback
        scopes:
          - openid
          - profile
          - email
          - groups
        token_endpoint_auth_method: client_secret_post
      - client_id: grafana
        client_name: Grafana
        client_secret: '{{ env "AUTH_GRAFANA_OIDC_CLIENT_SECRET" }}'
        claims_policy: 'grafana'
        consent_mode: implicit
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - https://grafana.the-lab.zone/login/generic_oauth
        scopes:
          - openid
          - profile
          - email
          - groups
        token_endpoint_auth_method: client_secret_basic
