---
- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: true

- name: restart sshd
  ansible.builtin.systemd:
    daemon_reload: true
  notify: restart ssh socket

- name: restart ssh socket
  ansible.builtin.shell: |
    systemctl stop ssh.service
    systemctl restart ssh.socket

- name: restart step-renewer after override
  ansible.builtin.systemd:
    name: step-renewer
    state: restarted
    daemon_reload: true
