all:
  vars:
    ansible_user: root
  children:
    lab:
      hosts:
        step-ca:
          ansible_host: 10.40.1.3
          app_role: step-ca
          use_common_role: false
        tailscale:
          ansible_host: 10.40.0.10
          ansible_ssh_common_args: "-o ProxyJump={{ lookup('env', 'PROXMOX_SSH_USERNAME') }}@{{ lookup('env', 'PROXMOX_SSH_HOST') }}"
          app_role: tailscale
          use_common_role: false
        coredns:
          ansible_host: 10.40.1.2
          app_role: coredns
        postgresql:
          ansible_host: 10.40.1.41
          app_role: postgresql
        garage:
          ansible_host: 10.40.1.11
          app_role: garage
        authelia:
          ansible_host: 10.40.1.4
          app_role: authelia
        caddy:
          ansible_host: 10.40.1.1
          ansible_port: 2222
          app_role: caddy
        zot:
          ansible_host: 10.40.1.31
          app_role: zot
        gitea:
          ansible_host: 10.40.1.21
          app_role: gitea
        valkey:
          ansible_host: 10.40.1.42
          app_role: valkey
