all:
  vars:
    ansible_user: root
  children:
    lab:
      hosts:
        tailscale:
          ansible_host: 10.40.0.10
          ansible_ssh_common_args: "-o ProxyJump={{ lookup('env', 'PROXMOX_SSH_USERNAME') }}@{{ lookup('env', 'PROXMOX_SSH_HOST') }}"
          app_role: tailscale
          use_common_role: false
