all:
  vars:
    ansible_user: root
  children:
    lab:
      hosts:
        tailscale:
          ansible_host: 10.40.0.10
          ansible_ssh_common_args: "-o ProxyJump={{ lookup('env', 'PROXMOX_SSH_USERNAME') }}@{{ lookup('env', 'PROXMOX_SSH_HOST') }}"
          app_role: tailscale
          use_common_role: false
        patroni-pg:
          ansible_host: 10.40.1.75
          ansible_user: debian
          ansible_ssh_common_args: "-o ProxyJump={{ lookup('env', 'PROXMOX_SSH_USERNAME') }}@{{ lookup('env', 'PROXMOX_SSH_HOST') }}"
          app_role: patroni
          use_common_role: false
        aistor:
          ansible_host: 10.40.1.20
          ansible_user: debian
          ansible_ssh_common_args: "-o ProxyJump={{ lookup('env', 'PROXMOX_SSH_USERNAME') }}@{{ lookup('env', 'PROXMOX_SSH_HOST') }}"
          ansible_python_interpreter: /usr/bin/python3
          app_role: aistor
          use_common_role: false
