# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

import:
  - catalog/_default.yaml

components:
  terraform:
    tailscale:
      metadata:
        terraform_workspace: "{{ .atmos_component }}"
      vars:
        tailscale:
          id: 400
          hostname: "tailscale"
          description: "Tailscale"
          ip_cidr: "192.168.40.40/24"
          routes:
            - "192.168.40.0/24"
        container:
          image:
            repository: "tailscale/tailscale"
            tag: "v1.92.5"
          resources:
            cpu: 1
            memory: 1024
            disk:
              size: 5