---
- name: restart garage
  ansible.builtin.systemd:
    name: garage
    state: restarted
    daemon_reload: true

- name: restart garage-webui
  ansible.builtin.systemd:
    name: garage-webui
    state: restarted
    daemon_reload: true
